### ISSUE TITLE
Error With Auto

### ISSUE THREAD

**Issue by StarDylan** [Team3256/Alpine#2]
﻿﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:34) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:10|0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60478 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60479 ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ -200 ﻿﻿ CTR: No new response to update signal ﻿﻿ Talon FX 5 ConfigSupplyCurrentLimit ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ -200 ﻿﻿ CTR: No new response to update signal ﻿﻿ Talon FX 5 ConfigSupplyCurrentLimit ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.RuntimeException: Failed to configure Falcon 500: SigNotUpdated ﻿﻿ com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11): Unhandled exception: java.lang.RuntimeException: Failed to configure Falcon 500: SigNotUpdated ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.Falcon500DriveControllerFactoryBuilder$FactoryImplementation.create(Falcon500DriveControllerFactoryBuilder.java:62) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.Falcon500DriveControllerFactoryBuilder$FactoryImplementation.create(Falcon500DriveControllerFactoryBuilder.java:44) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.DriveControllerFactory.create(DriveControllerFactory.java:19) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.SwerveModuleFactory.create(SwerveModuleFactory.java:27) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.Mk3SwerveModuleHelper.createFalcon500(Mk3SwerveModuleHelper.java:73) ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.Mk3SwerveModuleHelper.createFalcon500(Mk3SwerveModuleHelper.java:103) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.subsystems.SwerveDrive.<init>(SwerveDrive.java:54) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.RobotContainer.<init>(RobotContainer.java:21) ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:33) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:10|0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60490 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60491 ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿﻿ edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246): Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿﻿ frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39): Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer.timeParameterizeTrajectory(TrajectoryParameterizer.java:245) ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:100) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:129) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.AutoChooser.getDefaultChooser(AutoChooser.java:16) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.RobotContainer.getCommandChooser(RobotContainer.java:60) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:34) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:10|0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60502 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60503 ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿﻿ edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246): Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿﻿ frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39): Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer.timeParameterizeTrajectory(TrajectoryParameterizer.java:245) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:100) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:129) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.AutoChooser.getDefaultChooser(AutoChooser.java:16) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.RobotContainer.getCommandChooser(RobotContainer.java:60) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:34) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:10|0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60514 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 60515 ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ -200 ﻿﻿ CTR: No new response to update signal ﻿﻿ Talon FX 6 ConfigSelectedFeedbackSensor ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ -200 ﻿﻿ CTR: No new response to update signal ﻿﻿ Talon FX 6 ConfigSelectedFeedbackSensor ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.RuntimeException: Failed to configure Falcon 500 settings: SigNotUpdated ﻿﻿ com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11): Unhandled exception: java.lang.RuntimeException: Failed to configure Falcon 500 settings: SigNotUpdated ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.CtreUtils.checkCtreError(CtreUtils.java:11) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.Falcon500SteerControllerFactoryBuilder$FactoryImplementation.create(Falcon500SteerControllerFactoryBuilder.java:119) ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.ctre.Falcon500SteerControllerFactoryBuilder$FactoryImplementation.create(Falcon500SteerControllerFactoryBuilder.java:74) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.SteerControllerFactory.create(SteerControllerFactory.java:20) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.SwerveModuleFactory.create(SwerveModuleFactory.java:32) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.Mk3SwerveModuleHelper.createFalcon500(Mk3SwerveModuleHelper.java:73) ﻿
﻿﻿﻿﻿﻿﻿ 	at com.swervedrivespecialties.swervelib.Mk3SwerveModuleHelper.createFalcon500(Mk3SwerveModuleHelper.java:103) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.subsystems.SwerveDrive.<init>(SwerveDrive.java:54) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.RobotContainer.<init>(RobotContainer.java:21) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:33) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix] Library shutdown cleanly ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 0 ﻿﻿ [phoenix-diagnostics] Server shutdown cleanly. (dur:10|0) ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ********** Robot program starting ********** ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 55010 ﻿
﻿﻿﻿﻿﻿﻿ NT: server: client CONNECTED: 10.32.56.189 port 55012 ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿﻿ edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.DriverStation.reportJoystickUnplugged﻿Warning﻿(DriverStation.java:1246): Joystick Button 1 on port 0 not available, check if controller is plugged in ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿﻿ frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ Error at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39): Unhandled exception: edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer$TrajectoryGenerationException: Something went wrong at iteration 1 of time parameterization. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 1 ﻿﻿ Robots should not quit, but yours did! ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryParameterizer.timeParameterizeTrajectory(TrajectoryParameterizer.java:245) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:100) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator.generateTrajectory(TrajectoryGenerator.java:129) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.Paths.getTrajectory1(Paths.java:39) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.auto.AutoChooser.getDefaultChooser(AutoChooser.java:16) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.RobotContainer.getCommandChooser(RobotContainer.java:60) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Robot.robotInit(Robot.java:34) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:94) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:335) ﻿
﻿﻿﻿﻿﻿﻿ 	at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:407) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.team3256.robot.Main.main(Main.java:27) ﻿
﻿﻿﻿﻿﻿﻿  ﻿
﻿﻿﻿﻿﻿﻿ ﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿ Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352): The startCompetition() method (or methods called by it) should have handled the exception above. ﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44004 ﻿﻿ FRC:  The Driver Station has lost communication with the robot. ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44002 ﻿﻿ Ping Results:  link-bad,  DS radio(.4)-bad,  robot radio(.1)-bad,  roboRIO(.2)-bad,  FMS-bad FRC:  Driver Station ping status has changed. ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿Warning ﻿﻿ 44000 ﻿﻿ DS Disable ﻿﻿ Driver Station ﻿﻿﻿

**Comment by adityapawar1** [comment]
Might be because we forgot to define the auto constants

        public static double kMaxSpeedMetersPerSecond;
        public static double kMaxAccelerationMetersPerSecondSquared;
        public static double kPXController;
        public static TrapezoidProfile.Constraints kThetaControllerConstraints;
        public static double kPYController;

**Comment by adityapawar1** [comment]
Fixed in 684d075e7f6ed883e4da5df4b3ef1425d46af989
